


const samples = {

    geometry: {
        "header": [null],
        "rows":   [null,
                  ["Height", "h", "cm", [3]],
                  ["Radius", "rad", "cm", [2.5]],
                  ["Volume of Cylinder","vol", "cm^3", "h*3.14*rad*rad"],
                  null,
                  ["Sphere radius", "rad2", "cm", [5]],
                  ["Volume of sphere", "sphere", "cm^3", "4/3*PI*rad2^3"],
                  null,
                  ["Dog bone volume", "dogbone", "cm^3", "sphere*2+vol"],
                  null,
        ]
    },
    operators: {
        "header": ["scalar, scalar", "vector, vector", "scalar, vector", "vector, scalar", "boolean"],
        "rows":   [null,
                  ["======= This sheet can be modified, but not resaved.  Fiddle away", "", "", ""],
                  null,
                  ["First value",             "a", "",     [2, [2,3,4], 3, [1,2,3], true] ],
                  ["Second value",            "b", "cm",   [3.0, [1.0,-1,-2], [5.0,6.1,1], 2, false] ],
                  ["Third value",             "c", "",     [5, true, 4.1, [1,2], false] ],
                  null,
                  ["Multiply on vectors is cross product", 
                                              "cp",      "",   "a*b"],
                  ["Divide",                  "div",     "",   "a/b"],
                  ["Add",                     "add",     "",   "a+b"],
                  ["Subtract",                "sub",     "",   "a-b"],
                  ["Remainder",               "rem",     "",   "a%b"],
                  ["Power",                   "pwr",     "",   "a^b"],
                  null,
                  ["Dot product is @",        "dp",      "",   "a@b"],
                  null,
                  ["'in' operator",           "in_",     "",   "a in b"],
                  ["index operator",          "index",   "",   "a[b]"],
                  null,
                  ["And",                     "and_",   "",    "a and b"],
                  ["Or",                      "_or",    "",    "a or b"],
                  ["Not",                     "not_",   "",    "not a"],
                  ["Length",                  "length_", "",   "length(a)"],
                  null,
                  ["ref",                     "ref",    "",    "a"],
                  null,
                  ["sin",                     "sin_",   "",    "sin(a)"],
                  ["cos",                     "cos_",   "",    "cos(a)"],
                  ["tan",                     "tan_",   "",    "tan(a)"],
                  null,
                  ["asin",                    "asin_",  "",   "asin(a)"],
                  ["acos",                    "acos_",  "",   "acos(a)"],
                  ["atan",                    "atan_",  "",   "atan(a)"],
                  null,
                  ["sinh",                    "sinh_",  "",   "sinh(a)"],
                  ["cosh",                    "cosh_",  "",   "cosh(a)"],
                  ["tanh",                    "tanh_",  "",   "tanh(a)"],
                  null,
                  ["asinh",                   "asinh_", "",   "asinh(a)"],
                  ["acosh",                   "acosh_", "",   "acosh(a)"],
                  ["atanh",                   "atanh_", "",   "atanh(a)"],
                  null,
                  ['sqrt',                    "sqrt_",  "",   "sqrt(a)"],
                  ['cbrt',                    "cbrt_",  "",   "cbrt(a)"],
                  ['sign',                    "sign_",  "",   "sign(a)"],
                  ['abs',                     "abs_",   "",   "abs(a)"],
                  ['ceil',                    "ceil_",  "",   "ceil(a)"],
                  ['floor',                   "floor_", "",   "floor(a)"],
                  ['trunc',                   "trunc_", "",   "trunc(a)"],
                  ['round',                   "round_", "",   "round(a)"],
                  ['plus',                    "plus_",  "",   "+a"],
                  ['minus',                   "minus_", "",   "-a"],
                  null,
                  ["log",                     "log_",   "",   "log(a)"],
                  ["ln",                      "ln_",    "",   "ln(a)"],
                  ["log2",                    "log2_",  "",   "log2(a)"],
                  ["log10",                   "log10_", "",   "log10(a)"],
                  null,
                  ["expm1",                   "expm1_", "",   "expm1(a)"],
                  ["log1p",                   "log1p_", "",   "log1p(a)"],
                  ["exp",                     "exp_",   "",   "exp(a)"],
                  null,

        ]
    }
}


export { samples }