


const samples = {

    geometry: {
        "header": [null],
        "rows":   [null,
                  ["Height", "h", "cm", [3]],
                  ["Radius", "rad", "cm", [2.5]],
                  ["Volume of Cylinder","vol", "cm^3", "h*3.14*rad*rad"],
                  null,
                  ["Sphere radius", "rad2", "cm", [5]],
                  ["Volume of sphere", "sphere", "cm^3", "4/3*pi*rad2^3"],
                  null,
                  ["Dog bone volume", "dogbone", "cm^3", "sphere*2+vol"],
                  null,
        ]
    },
    numbers: {
        "header": [null],
        "rows":   [null,
                  ["This sheet can be modified, but not resaved.  Fiddle away", "", "==", ""],
                  null,
                  ["First value",             "a",          "cm",   [5.003] ],
                  ["Second value",            "b",          "cm",   [3.0] ],
                  ["Third value",             "c",          "",     [2] ],
                  ["Vector",                  "v",          "",   [[1,2,3]] ],
                  null,
                  ["Multiply ",               "cp",         "",   "a*b"],
                  ["Divide",                  "div",        "",   "a/b"],
                  ["Add",                     "add",        "",   "a+b"],
                  ["Subtract",                "sub",        "",   "a-b"],
                  ["Remainder",               "rem",        "",   "a%b"],
                  ["Power",                   "pwr",        "",   "a^c"],
                  null,
                  ["'in' operator",           "in_",        "",   "c in v"],
                  ["index operator",          "index",      "",   "v[c]"],
                  null,
                  ["equals",                  "eq",         "",  "a == b"],
                  ["not equal",               "neq",        "",  "a != b"],
                  ["greater than",            "gt",         "",  "a > b"],
                  ["less than",               "lt",         "",  "a < b"],
                  ["greater or equal",        "ge",         "",  "a >= b"],
                  ["less than or equal",      "le",         "",  "a <= b"],
    
                  null,
                  ["sin",                     "sin_",       "",    "sin(c)"],
                  ["cos",                     "cos_",       "",    "cos(c)"],
                  ["tan",                     "tan_",       "",    "tan(c)"],
                  null,
                  ["asin",                    "asin_",      "",   "asin(c/3)"],
                  ["acos",                    "acos_",      "",   "acos(c/3)"],
                  ["atan",                    "atan_",      "",   "atan(c/3)"],
                  null,
                  ["sinh",                    "sinh_",      "",   "sinh(c)"],
                  ["cosh",                    "cosh_",      "",   "cosh(c)"],
                  ["tanh",                    "tanh_",      "",   "tanh(c)"],
                  null,
                  ["asinh",                   "asinh_",     "",   "asinh(c)"],
                  ["acosh",                   "acosh_",     "",   "acosh(c)"],
                  ["atanh",                   "atanh_",     "",   "atanh(c/3)"],
                  null,
                  ['square root',             "sqrt_",      "",   "sqrt(a)"],
                  ['cube root',               "cbrt_",      "",   "cbrt(a)"],
                  ['sign',                    "sign_",      "",   "sign(a)"],
                  ['absolute value',          "abs_",       "",   "abs(a)"],
                  ['ceiling',                 "ceil_",      "",   "ceil(a)"],
                  ['floor',                   "floor_",     "",   "floor(a)"],
                  ['truncate',                "trunc_",     "",   "trunc(a)"],
//                  ['round (unary)',           "round_",     "",   "round(a)"],
                  ['plus',                    "plus_",      "",   "+a"],
                  ['minus',                   "minus_",     "",   "-a"],
                  null,
                  ["log (same as ln)",        "log_",       "",   "log(c)"],
                  ["ln (also log)",           "ln_",        "",   "ln(c)"],
                  ["log base 2",              "log2_",      "",   "log2(c)"],
                  null,

                  ["Round To",                "round_to",   "",     "roundTo(a,c)"],
                  ["Minimum",                 "min_",       "",     "min(a,b)"],
                  ["Maximum",                 "max_",       "",     "max(a,b)"],
                  null,
                  ["factorial",               "fac",         "",    "fac(c)"],
                  ['atan2',                   "atan2",       "",    "atan2(a,b)"],
                  ['hypot',                   "hypot_",      "",    "hypot(a,b)"],
                  null,
    
                  ["? : ",                    "t",          "",     "true ? b : a"],
        ]
    },
    boolean: {
        "header": [null],
        "rows":   [null,
                  ["This sheet can be modified, but not resaved.  Fiddle away", "", "==", ""],
                  null,
                  ["First value",             "a",          "",     [true] ],
                  ["Second value",            "b",          "",     [false] ],
                  null,
                  ["And",                     "and_",       "",    "a and b"],
                  ["Or",                      "_or",        "",    "a or b"],
                  ["Not",                     "not_",       "",    "not a"],
                  null,
                  ["equals",                  "eq",         "",  "a == b"],
                  ["not equal",               "neq",        "",  "a != b"],
    
                  null,
                  ["? : ",                    "t",          "",     "a ? b : a"],
                  null,
                  ["? : ",                    "t1",         "",     " not a ? b : a"],
    //              null,
    //              ["? : ",                    "t2",         "",     'true ? hi : bye'],
        ]
    },
    vectors: {
        "header": [null],
        "rows":   [null,
                  ["This sheet can be modified, but not resaved.  Fiddle away", "", "==", ""],
                  null,
                  ["First value",             "a",          "cm",     [[2,3,4], ] ],
                  ["Second value",            "b",          "cm",     [[1.0,-1,-2], ]],
                  ["Third value",             "v",           "",      [[1.0,-1,-2], ]],
                  ["Scalar value",            "c",           "",      [2], ],
                  null,
                  ["Multiply on vectors is cross product", "cp",         "",   "a*b"],
                  ["Divide",                  "div",        "",   "a/c"],
                  ["Add",                     "add",        "",   "a+b"],
                  ["Subtract",                "sub",        "",   "a-b"],
                  null,
                  ["Dot product is @",        "dp",         "",   "a@b"],
                  null,
                  ["'in' operator",           "in_",        "",   "c in v"],
                  ["index operator",          "index",      "",   "v[c]"],
                  null,
                  ["Length",                  "length_",    "",   "length(a)"],
                  null,
                  ["equals",                  "eq",         "",  "a == b"],
                  ["not equal",               "neq",        "",  "a != b"],
    
                  ['plus',                    "plus_",      "",   "+a"],
                  ['minus',                   "minus_",     "",   "-a"],
                  null,

                  ["Minimum",                 "min_a",       "",    "min(a)"],
                  ["Maximum",                 "max_a",       "",    "max(a)"],
                  null,
                  ["? : ",                    "t2",         "",     "true ? b : a"],
        ]
    }
}


export { samples }